- name: Deploy web app
  hosts: ansible01
  tasks:

    - name: install dependencies
      apt: 
        pkg: ['python', 'python-setuptools', 'python-dev', 'build-essential', 'python-pip', 'python-pymysql']
        
    - name: install mysql
      apt:
        pkg: ['default-mysql-server', 'default-mysql-client']

    - name: Start MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create /root/.my.cnf file
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600
      become: yes

    - name: Create DB
      community.mysql.mysql_db: 
        check_implicit_admin: yes
        login_user: root
        login_password: 123
        name: employee_db
        state: present

    - name: Create DB user
      mysql_user:
        name: db_user
        password: 123
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install flask
      pip:
        name: ['flask', 'flask-mysql']
