---
- hosts: webservers
  become: yes

  tasks:
  - debug:
      var: target_service
  - name: "lastest {{ target_service }} install"
    yum: 
      name: "{{ target_service }}"
      state: latest
    notify:
      - restart httpd # same string
  - name: create index.html
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add content
    lineinfile:
      regexp: "here is some content"
      line: "<h1>here is some content</h><br>{{ ansible_hostname }}"
      path: /var/www/html/index.html
    register: task_debug #name of var
  - debug:
      msg: "Output of linfile: {{ task_debug }}"
  handlers:
  - name: Attempt to restart httpd
    service:
      name: "{{ target_service }}"
      state: restarted
    listen: "restart httpd" # same string
