- hosts: localhost
  gather_facts: yes
  vars_files:
    - ../keys.yaml
  tasks:
    - name: get instances
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: Testing
      register: ec2_facts
    - debug:
        var: ec2_facts.instances[0].instance_id

    - name: remove tags
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        resource: "{{ ec2_facts.instances[0].instance_id }}"
        tags:
          Name: 
        state: absent

    - name: terminate instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        state: absent
        instance_id:
          - "{{ ec2_facts.instances[0].instance_id }}"
      register: ec2

    - debug:
        var: ec2
