- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yaml
  tasks:
    - name: get demo instance
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY_ID }}"
        ec2_region: "{{ AWS_REGION }}"

