# index of vpc changes, not sure why. sometimes 1 is the default vpc, cant see a pattern or anything on docs
# how to keep track of ids without keep geting info
- hosts: localhost
  gather_facts: no
  vars_files:
    - ../keys.yaml
  tasks:
    - name: create VPC
      ec2_vpc_net:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        name: Intra-VPC
        cidr_block: 10.192.0.0/16
        tags:
          Name: Intranet

    - name: get VPC ID
      ec2_vpc_net_info:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
      register: vpc_info
    - debug: 
        var: vpc_info.vpcs[1].vpc_id

    - name: create subnet1
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        state: present
        vpc_id: "{{ vpc_info.vpcs[1].vpc_id }}"
        cidr: 10.192.1.0/24
        az: us-east-1a
        tags:
          Name: frontend_us-east-1a

    - name: get subnet1 ID
      ec2_vpc_subnet_info:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[1].vpc_id }}"
      register: subnet_info
    - debug: 
        var: subnet_info.subnets[0].id

    - name: create subnet2
      ec2_vpc_subnet:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        state: present
        vpc_id: "{{ vpc_info.vpcs[1].vpc_id }}"
        cidr: 10.192.2.0/24
        az: us-east-1b
        tags:
          Name: frontend_us-east-1b

    - name: get subnet2 ID
      ec2_vpc_subnet_info:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[1].vpc_id }}"
      register: subnet_info
    - debug: 
        var: subnet_info.subnets[1].id

