- hosts: localhost
  gather_facts: no
  vars_files:
    - ../keys.yaml
  tasks:
    - name: get amis based on a description
      ec2_ami_info:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
#       image_ids: ami-01c3657c191c71f94
        filters:
          description: "*ECS*Optimized*Linux 2*"
      register: ami_facts
    - name: output info
      debug:
        msg: "{{ item.description }}"
      loop_control:
        label: "{{ item.image_id }}"
      loop: "{{ ami_facts.images }}"
