- hosts: localhost
  gather_facts: no
  vars_files:
    - ../keys.yaml
  tasks:
    - name: create ami
      ec2_ami:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        aws_region: "{{ AWS_REGION }}"
        instance_id: i-0d2f8ab54b7f283ea
        name: ansibleAMI
        state: present
